prog:gererparking1.o maingererparking1.o
	gcc gererparking1.o maingererparking1.o -o prog
maingererparking1.o:maingererparking1.c
	gcc -c maingererparking1.c
gererparking1.o:gererparking1.c
	gcc -c gererparking1.c
