/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_w1 (void);
GtkWidget* create_dialogsupprimerparking (void);
GtkWidget* create_dialogobserverparking (void);
GtkWidget* create_dialogajoutparking (void);
GtkWidget* create_dialogaffecteragent (void);
GtkWidget* create_dialogmodifparking (void);
GtkWidget* create_Parky (void);
GtkWidget* create_dialogmodify (void);
GtkWidget* create_Parky_citoyen (void);
GtkWidget* create_dialogmodifyagent (void);
