/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *w1;
  GtkWidget *Parky;
  GtkWidget *dialogsupprimerparking;
  GtkWidget *dialogobserverparking;
  GtkWidget *dialogajoutparking;
  GtkWidget *dialogaffecteragent;
  GtkWidget *dialogmodifparking;
  GtkWidget *framep;
  GtkWidget *framea;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  w1 = create_w1 ();
  //gtk_widget_show (w1);
  dialogsupprimerparking = create_dialogsupprimerparking ();
  //gtk_widget_show (dialogsupprimerparking);
  dialogobserverparking = create_dialogobserverparking ();
  //gtk_widget_show (dialogobserverparking);
  dialogajoutparking = create_dialogajoutparking ();
  //gtk_widget_show (dialogajoutparking);
  dialogaffecteragent = create_dialogaffecteragent ();
  //gtk_widget_show (dialogaffecteragent);
  dialogmodifparking = create_dialogmodifparking ();
  //gtk_widget_show (dialogajoutparking)
  Parky = create_Parky ();
  gtk_widget_show (Parky);

  // Initially hide the GtkFixed widget
    framep = lookup_widget(Parky, "frameparking");
    gtk_widget_hide(framep);
    framea = lookup_widget(Parky, "framea");
    gtk_widget_hide(framea);	
  
  gtk_main ();
  return 0;
}

