/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_w4espacecitoyen (void);
GtkWidget* create_dialogSuppCpt (void);
GtkWidget* create_authentification (void);
GtkWidget* create_w1espaceadmin (void);
GtkWidget* create_w5 (void);
GtkWidget* create_w3 (void);
GtkWidget* create_w6 (void);
GtkWidget* create_w4 (void);
GtkWidget* create_w2 (void);
GtkWidget* create_inscription (void);
GtkWidget* create_w4listeCit (void);
GtkWidget* create_w1 (void);
GtkWidget* create_dialogsupprimerparking (void);
GtkWidget* create_dialogobserverparking (void);
GtkWidget* create_dialogajoutparking (void);
GtkWidget* create_dialogaffecteragent (void);
GtkWidget* create_aboutdialog1 (void);
